name: Update GitHub Stats

on:
  schedule:
    - cron: "0 18 * * *"

  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/github-stats.js
      - name: Generate Stats SVG
        run: node scripts/generate-svg.js
